name: Runtime Security Testing

on:
  workflow_call:
    inputs:
      environment:
        description: "Environment to test"
        required: true
        type: string
      app-url:
        description: "Application URL to test"
        required: true
        type: string
    secrets:
      AWS_IAM_ROLE_ARN:
        description: "AWS IAM Role ARN for authentication"
        required: true
    outputs:
      runtime-infra-scan-result:
        description: "Runtime infrastructure scan result"
        value: ${{ jobs.runtime-infra-scan.outputs.result }}

jobs:
  runtime-infra-scan:
    name: Runtime Infrastructure Scan with Prowler
    runs-on: ubuntu-latest
    outputs:
      result: ${{ steps.scan-result.outputs.result }}
    steps:
      - name: Check out code
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2
        with:
          fetch-depth: 0
          persist-credentials: false

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@ececac1a45f3b08a01d2dd070d28d111c5fe6722 # v4.1.0
        with:
            role-to-assume: ${{ secrets.AWS_IAM_ROLE_ARN }}
            role-session-name: ProwlerSession
            aws-region: ${{ vars.AWS_REGION }}
            role-duration-seconds: ${{ vars.AWS_IAM_ROLE_SESSION_DURATION }}
            mask-aws-account-id: true

      - name: Install Prowler
        run: |
            pipx install prowler
            prowler -v

      - name: Run Prowler
        id: prowler
        run: |
            prowler aws --service iam s3 --output-formats html -z
        continue-on-error: true

      - name: Message
        run: |
            echo "Prowler run completed"

      - name: Upload Prowler HTML Report
        uses: actions/upload-artifact@ea165f8d65b6e75b540449e92b4886f43607fa02 # v4.6.2
        if: always()
        with:
          name: prowler-html-report
          path: output/*.html
          retention-days: 3

      - name: Set scan result
        id: scan-result
        if: always()
        run: |
          if [ "${{ steps.prowler.outcome }}" == "success" ]; then
            echo "result=success" >> "$GITHUB_OUTPUT"
            echo "✅ Pipeline scan passed"
          else
            echo "result=failure" >> "$GITHUB_OUTPUT"
            echo "❌ Pipeline scan failed"
          fi
